/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LocaleIndexImport } from './routes/$locale/index'
import { Route as LocaleAboutImport } from './routes/$locale/about'
import { Route as LocaleCatalogShopImport } from './routes/$locale/_catalog/shop'
import { Route as LocaleAuthResetPasswordImport } from './routes/$locale/_auth/reset-password'
import { Route as LocaleAuthRegisterImport } from './routes/$locale/_auth/register'
import { Route as LocaleAuthLoginImport } from './routes/$locale/_auth/login'
import { Route as LocaleAuthForgetPasswordImport } from './routes/$locale/_auth/forget-password'
import { Route as LocaleCatalogCategoriesIndexImport } from './routes/$locale/_catalog/categories/index'
import { Route as LocaleCatalogCategoriesSlugImport } from './routes/$locale/_catalog/categories/$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LocaleIndexRoute = LocaleIndexImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRoute,
} as any)

const LocaleAboutRoute = LocaleAboutImport.update({
  id: '/$locale/about',
  path: '/$locale/about',
  getParentRoute: () => rootRoute,
} as any)

const LocaleCatalogShopRoute = LocaleCatalogShopImport.update({
  id: '/$locale/_catalog/shop',
  path: '/$locale/shop',
  getParentRoute: () => rootRoute,
} as any)

const LocaleAuthResetPasswordRoute = LocaleAuthResetPasswordImport.update({
  id: '/$locale/_auth/reset-password',
  path: '/$locale/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const LocaleAuthRegisterRoute = LocaleAuthRegisterImport.update({
  id: '/$locale/_auth/register',
  path: '/$locale/register',
  getParentRoute: () => rootRoute,
} as any)

const LocaleAuthLoginRoute = LocaleAuthLoginImport.update({
  id: '/$locale/_auth/login',
  path: '/$locale/login',
  getParentRoute: () => rootRoute,
} as any)

const LocaleAuthForgetPasswordRoute = LocaleAuthForgetPasswordImport.update({
  id: '/$locale/_auth/forget-password',
  path: '/$locale/forget-password',
  getParentRoute: () => rootRoute,
} as any)

const LocaleCatalogCategoriesIndexRoute =
  LocaleCatalogCategoriesIndexImport.update({
    id: '/$locale/_catalog/categories/',
    path: '/$locale/categories/',
    getParentRoute: () => rootRoute,
  } as any)

const LocaleCatalogCategoriesSlugRoute =
  LocaleCatalogCategoriesSlugImport.update({
    id: '/$locale/_catalog/categories/$slug',
    path: '/$locale/categories/$slug',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/$locale/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutImport
      parentRoute: typeof rootRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleIndexImport
      parentRoute: typeof rootRoute
    }
    '/$locale/_auth/forget-password': {
      id: '/$locale/_auth/forget-password'
      path: '/$locale/forget-password'
      fullPath: '/$locale/forget-password'
      preLoaderRoute: typeof LocaleAuthForgetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/$locale/_auth/login': {
      id: '/$locale/_auth/login'
      path: '/$locale/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleAuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/$locale/_auth/register': {
      id: '/$locale/_auth/register'
      path: '/$locale/register'
      fullPath: '/$locale/register'
      preLoaderRoute: typeof LocaleAuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/$locale/_auth/reset-password': {
      id: '/$locale/_auth/reset-password'
      path: '/$locale/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocaleAuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/$locale/_catalog/shop': {
      id: '/$locale/_catalog/shop'
      path: '/$locale/shop'
      fullPath: '/$locale/shop'
      preLoaderRoute: typeof LocaleCatalogShopImport
      parentRoute: typeof rootRoute
    }
    '/$locale/_catalog/categories/$slug': {
      id: '/$locale/_catalog/categories/$slug'
      path: '/$locale/categories/$slug'
      fullPath: '/$locale/categories/$slug'
      preLoaderRoute: typeof LocaleCatalogCategoriesSlugImport
      parentRoute: typeof rootRoute
    }
    '/$locale/_catalog/categories/': {
      id: '/$locale/_catalog/categories/'
      path: '/$locale/categories'
      fullPath: '/$locale/categories'
      preLoaderRoute: typeof LocaleCatalogCategoriesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/forget-password': typeof LocaleAuthForgetPasswordRoute
  '/$locale/login': typeof LocaleAuthLoginRoute
  '/$locale/register': typeof LocaleAuthRegisterRoute
  '/$locale/reset-password': typeof LocaleAuthResetPasswordRoute
  '/$locale/shop': typeof LocaleCatalogShopRoute
  '/$locale/categories/$slug': typeof LocaleCatalogCategoriesSlugRoute
  '/$locale/categories': typeof LocaleCatalogCategoriesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/forget-password': typeof LocaleAuthForgetPasswordRoute
  '/$locale/login': typeof LocaleAuthLoginRoute
  '/$locale/register': typeof LocaleAuthRegisterRoute
  '/$locale/reset-password': typeof LocaleAuthResetPasswordRoute
  '/$locale/shop': typeof LocaleCatalogShopRoute
  '/$locale/categories/$slug': typeof LocaleCatalogCategoriesSlugRoute
  '/$locale/categories': typeof LocaleCatalogCategoriesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/_auth/forget-password': typeof LocaleAuthForgetPasswordRoute
  '/$locale/_auth/login': typeof LocaleAuthLoginRoute
  '/$locale/_auth/register': typeof LocaleAuthRegisterRoute
  '/$locale/_auth/reset-password': typeof LocaleAuthResetPasswordRoute
  '/$locale/_catalog/shop': typeof LocaleCatalogShopRoute
  '/$locale/_catalog/categories/$slug': typeof LocaleCatalogCategoriesSlugRoute
  '/$locale/_catalog/categories/': typeof LocaleCatalogCategoriesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale/about'
    | '/$locale'
    | '/$locale/forget-password'
    | '/$locale/login'
    | '/$locale/register'
    | '/$locale/reset-password'
    | '/$locale/shop'
    | '/$locale/categories/$slug'
    | '/$locale/categories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/about'
    | '/$locale'
    | '/$locale/forget-password'
    | '/$locale/login'
    | '/$locale/register'
    | '/$locale/reset-password'
    | '/$locale/shop'
    | '/$locale/categories/$slug'
    | '/$locale/categories'
  id:
    | '__root__'
    | '/'
    | '/$locale/about'
    | '/$locale/'
    | '/$locale/_auth/forget-password'
    | '/$locale/_auth/login'
    | '/$locale/_auth/register'
    | '/$locale/_auth/reset-password'
    | '/$locale/_catalog/shop'
    | '/$locale/_catalog/categories/$slug'
    | '/$locale/_catalog/categories/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAuthForgetPasswordRoute: typeof LocaleAuthForgetPasswordRoute
  LocaleAuthLoginRoute: typeof LocaleAuthLoginRoute
  LocaleAuthRegisterRoute: typeof LocaleAuthRegisterRoute
  LocaleAuthResetPasswordRoute: typeof LocaleAuthResetPasswordRoute
  LocaleCatalogShopRoute: typeof LocaleCatalogShopRoute
  LocaleCatalogCategoriesSlugRoute: typeof LocaleCatalogCategoriesSlugRoute
  LocaleCatalogCategoriesIndexRoute: typeof LocaleCatalogCategoriesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAuthForgetPasswordRoute: LocaleAuthForgetPasswordRoute,
  LocaleAuthLoginRoute: LocaleAuthLoginRoute,
  LocaleAuthRegisterRoute: LocaleAuthRegisterRoute,
  LocaleAuthResetPasswordRoute: LocaleAuthResetPasswordRoute,
  LocaleCatalogShopRoute: LocaleCatalogShopRoute,
  LocaleCatalogCategoriesSlugRoute: LocaleCatalogCategoriesSlugRoute,
  LocaleCatalogCategoriesIndexRoute: LocaleCatalogCategoriesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$locale/about",
        "/$locale/",
        "/$locale/_auth/forget-password",
        "/$locale/_auth/login",
        "/$locale/_auth/register",
        "/$locale/_auth/reset-password",
        "/$locale/_catalog/shop",
        "/$locale/_catalog/categories/$slug",
        "/$locale/_catalog/categories/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$locale/about": {
      "filePath": "$locale/about.tsx"
    },
    "/$locale/": {
      "filePath": "$locale/index.tsx"
    },
    "/$locale/_auth/forget-password": {
      "filePath": "$locale/_auth/forget-password.tsx"
    },
    "/$locale/_auth/login": {
      "filePath": "$locale/_auth/login.tsx"
    },
    "/$locale/_auth/register": {
      "filePath": "$locale/_auth/register.tsx"
    },
    "/$locale/_auth/reset-password": {
      "filePath": "$locale/_auth/reset-password.tsx"
    },
    "/$locale/_catalog/shop": {
      "filePath": "$locale/_catalog/shop.tsx"
    },
    "/$locale/_catalog/categories/$slug": {
      "filePath": "$locale/_catalog/categories/$slug.tsx"
    },
    "/$locale/_catalog/categories/": {
      "filePath": "$locale/_catalog/categories/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
